version: '3.1'

services:
  db:
    image: mysql:8.0
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: kanbam_db

  adminer:
    image: adminer
    ports:
      - 8000:8080

volumes:
  dbbase: